version: '3.1'
volumes:
  postgres:
    driver: local

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - ${DB_LOCAL_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"