// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ova-meeting-api/api.proto

package ova_meeting_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddMeetingRequestV1 struct {
	Userid               uint64          `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	State                *MeetingStateV1 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Users                *MeetingUsersV1 `protobuf:"bytes,4,opt,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddMeetingRequestV1) Reset()         { *m = AddMeetingRequestV1{} }
func (m *AddMeetingRequestV1) String() string { return proto.CompactTextString(m) }
func (*AddMeetingRequestV1) ProtoMessage()    {}
func (*AddMeetingRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{0}
}

func (m *AddMeetingRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMeetingRequestV1.Unmarshal(m, b)
}
func (m *AddMeetingRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMeetingRequestV1.Marshal(b, m, deterministic)
}
func (m *AddMeetingRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMeetingRequestV1.Merge(m, src)
}
func (m *AddMeetingRequestV1) XXX_Size() int {
	return xxx_messageInfo_AddMeetingRequestV1.Size(m)
}
func (m *AddMeetingRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMeetingRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_AddMeetingRequestV1 proto.InternalMessageInfo

func (m *AddMeetingRequestV1) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *AddMeetingRequestV1) GetState() *MeetingStateV1 {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *AddMeetingRequestV1) GetUsers() *MeetingUsersV1 {
	if m != nil {
		return m.Users
	}
	return nil
}

type MeetingIDRequestV1 struct {
	Id                   *UUID    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeetingIDRequestV1) Reset()         { *m = MeetingIDRequestV1{} }
func (m *MeetingIDRequestV1) String() string { return proto.CompactTextString(m) }
func (*MeetingIDRequestV1) ProtoMessage()    {}
func (*MeetingIDRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{1}
}

func (m *MeetingIDRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeetingIDRequestV1.Unmarshal(m, b)
}
func (m *MeetingIDRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeetingIDRequestV1.Marshal(b, m, deterministic)
}
func (m *MeetingIDRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeetingIDRequestV1.Merge(m, src)
}
func (m *MeetingIDRequestV1) XXX_Size() int {
	return xxx_messageInfo_MeetingIDRequestV1.Size(m)
}
func (m *MeetingIDRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_MeetingIDRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_MeetingIDRequestV1 proto.InternalMessageInfo

func (m *MeetingIDRequestV1) GetId() *UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

type MeetingStateV1 struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeetingStateV1) Reset()         { *m = MeetingStateV1{} }
func (m *MeetingStateV1) String() string { return proto.CompactTextString(m) }
func (*MeetingStateV1) ProtoMessage()    {}
func (*MeetingStateV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{2}
}

func (m *MeetingStateV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeetingStateV1.Unmarshal(m, b)
}
func (m *MeetingStateV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeetingStateV1.Marshal(b, m, deterministic)
}
func (m *MeetingStateV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeetingStateV1.Merge(m, src)
}
func (m *MeetingStateV1) XXX_Size() int {
	return xxx_messageInfo_MeetingStateV1.Size(m)
}
func (m *MeetingStateV1) XXX_DiscardUnknown() {
	xxx_messageInfo_MeetingStateV1.DiscardUnknown(m)
}

var xxx_messageInfo_MeetingStateV1 proto.InternalMessageInfo

func (m *MeetingStateV1) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MeetingStateV1) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MeetingUsersV1 struct {
	Users                []uint64 `protobuf:"varint,1,rep,packed,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeetingUsersV1) Reset()         { *m = MeetingUsersV1{} }
func (m *MeetingUsersV1) String() string { return proto.CompactTextString(m) }
func (*MeetingUsersV1) ProtoMessage()    {}
func (*MeetingUsersV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{3}
}

func (m *MeetingUsersV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeetingUsersV1.Unmarshal(m, b)
}
func (m *MeetingUsersV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeetingUsersV1.Marshal(b, m, deterministic)
}
func (m *MeetingUsersV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeetingUsersV1.Merge(m, src)
}
func (m *MeetingUsersV1) XXX_Size() int {
	return xxx_messageInfo_MeetingUsersV1.Size(m)
}
func (m *MeetingUsersV1) XXX_DiscardUnknown() {
	xxx_messageInfo_MeetingUsersV1.DiscardUnknown(m)
}

var xxx_messageInfo_MeetingUsersV1 proto.InternalMessageInfo

func (m *MeetingUsersV1) GetUsers() []uint64 {
	if m != nil {
		return m.Users
	}
	return nil
}

type ListMeetingsResponseV1 struct {
	Items                []*MeetingResponseV1 `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListMeetingsResponseV1) Reset()         { *m = ListMeetingsResponseV1{} }
func (m *ListMeetingsResponseV1) String() string { return proto.CompactTextString(m) }
func (*ListMeetingsResponseV1) ProtoMessage()    {}
func (*ListMeetingsResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{4}
}

func (m *ListMeetingsResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMeetingsResponseV1.Unmarshal(m, b)
}
func (m *ListMeetingsResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMeetingsResponseV1.Marshal(b, m, deterministic)
}
func (m *ListMeetingsResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMeetingsResponseV1.Merge(m, src)
}
func (m *ListMeetingsResponseV1) XXX_Size() int {
	return xxx_messageInfo_ListMeetingsResponseV1.Size(m)
}
func (m *ListMeetingsResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMeetingsResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_ListMeetingsResponseV1 proto.InternalMessageInfo

func (m *ListMeetingsResponseV1) GetItems() []*MeetingResponseV1 {
	if m != nil {
		return m.Items
	}
	return nil
}

type MeetingResponseV1 struct {
	Id                   *UUID           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Userid               uint64          `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	State                *MeetingStateV1 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Users                *MeetingUsersV1 `protobuf:"bytes,4,opt,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MeetingResponseV1) Reset()         { *m = MeetingResponseV1{} }
func (m *MeetingResponseV1) String() string { return proto.CompactTextString(m) }
func (*MeetingResponseV1) ProtoMessage()    {}
func (*MeetingResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{5}
}

func (m *MeetingResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeetingResponseV1.Unmarshal(m, b)
}
func (m *MeetingResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeetingResponseV1.Marshal(b, m, deterministic)
}
func (m *MeetingResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeetingResponseV1.Merge(m, src)
}
func (m *MeetingResponseV1) XXX_Size() int {
	return xxx_messageInfo_MeetingResponseV1.Size(m)
}
func (m *MeetingResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_MeetingResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_MeetingResponseV1 proto.InternalMessageInfo

func (m *MeetingResponseV1) GetId() *UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *MeetingResponseV1) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *MeetingResponseV1) GetState() *MeetingStateV1 {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *MeetingResponseV1) GetUsers() *MeetingUsersV1 {
	if m != nil {
		return m.Users
	}
	return nil
}

type UUID struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}
func (*UUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{6}
}

func (m *UUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUID.Unmarshal(m, b)
}
func (m *UUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUID.Marshal(b, m, deterministic)
}
func (m *UUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUID.Merge(m, src)
}
func (m *UUID) XXX_Size() int {
	return xxx_messageInfo_UUID.Size(m)
}
func (m *UUID) XXX_DiscardUnknown() {
	xxx_messageInfo_UUID.DiscardUnknown(m)
}

var xxx_messageInfo_UUID proto.InternalMessageInfo

func (m *UUID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*AddMeetingRequestV1)(nil), "ova.meeting.api.AddMeetingRequestV1")
	proto.RegisterType((*MeetingIDRequestV1)(nil), "ova.meeting.api.MeetingIDRequestV1")
	proto.RegisterType((*MeetingStateV1)(nil), "ova.meeting.api.MeetingStateV1")
	proto.RegisterType((*MeetingUsersV1)(nil), "ova.meeting.api.MeetingUsersV1")
	proto.RegisterType((*ListMeetingsResponseV1)(nil), "ova.meeting.api.ListMeetingsResponseV1")
	proto.RegisterType((*MeetingResponseV1)(nil), "ova.meeting.api.MeetingResponseV1")
	proto.RegisterType((*UUID)(nil), "ova.meeting.api.UUID")
}

func init() { proto.RegisterFile("ova-meeting-api/api.proto", fileDescriptor_648ecbe2c3874e1d) }

var fileDescriptor_648ecbe2c3874e1d = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0x13, 0xa7, 0x6a, 0x6f, 0x44, 0x42, 0xa6, 0x10, 0x82, 0xa9, 0x44, 0x34, 0xbc, 0x22,
	0xa4, 0xda, 0x4a, 0xa0, 0x02, 0x89, 0x15, 0x10, 0x16, 0x91, 0x60, 0x33, 0x28, 0x59, 0xb0, 0x9b,
	0xc4, 0x83, 0x3b, 0x22, 0xf6, 0xb8, 0x99, 0xb1, 0x25, 0x58, 0xf2, 0x0b, 0x2c, 0xf9, 0x0a, 0xfe,
	0x80, 0x7f, 0xe0, 0x17, 0xf8, 0x10, 0x34, 0x8f, 0xb4, 0x21, 0x0f, 0x54, 0x76, 0xdd, 0xf9, 0xfa,
	0x9e, 0x7b, 0xcf, 0x39, 0xe3, 0x33, 0x86, 0xdb, 0xa2, 0xa4, 0xc7, 0x29, 0x63, 0x8a, 0x67, 0xc9,
	0x31, 0xcd, 0x79, 0x44, 0x73, 0x1e, 0xe6, 0x0b, 0xa1, 0x04, 0x6a, 0x8a, 0x92, 0x86, 0xae, 0x15,
	0xd2, 0x9c, 0x07, 0x47, 0x89, 0x10, 0xc9, 0x9c, 0x45, 0x06, 0x96, 0x65, 0x42, 0x51, 0xc5, 0x45,
	0x26, 0x2d, 0x3c, 0xb8, 0xe3, 0xba, 0xa6, 0x9a, 0x16, 0x1f, 0x23, 0x96, 0xe6, 0xea, 0xb3, 0x6d,
	0xe2, 0xef, 0x1e, 0x1c, 0xbe, 0x8c, 0xe3, 0x77, 0x76, 0x1b, 0x61, 0x67, 0x05, 0x93, 0x6a, 0xd2,
	0x47, 0x6d, 0xd8, 0x2b, 0x24, 0x5b, 0xf0, 0xb8, 0x53, 0xe9, 0x7a, 0x3d, 0x9f, 0xb8, 0x0a, 0x9d,
	0x40, 0x4d, 0x2a, 0xaa, 0x58, 0xa7, 0xda, 0xf5, 0x7a, 0xf5, 0xc1, 0xdd, 0x70, 0x4d, 0x4b, 0xe8,
	0x36, 0xbd, 0xd7, 0xa0, 0x49, 0x9f, 0x58, 0xb4, 0x1e, 0xd3, 0x0b, 0x64, 0xc7, 0xff, 0xf7, 0xd8,
	0x58, 0x83, 0xf4, 0x98, 0x41, 0xe3, 0x17, 0x80, 0x5c, 0x63, 0x34, 0xbc, 0xd0, 0xf6, 0x00, 0x2a,
	0x3c, 0xee, 0x78, 0x66, 0xd3, 0xcd, 0x8d, 0x4d, 0xe3, 0xf1, 0x68, 0x48, 0x2a, 0x3c, 0xc6, 0x4f,
	0xa1, 0xf1, 0xb7, 0x18, 0xd4, 0x38, 0x1f, 0xf4, 0x35, 0x02, 0x21, 0xf0, 0x33, 0x9a, 0x32, 0x63,
	0xf1, 0x80, 0x98, 0x67, 0xfc, 0xf0, 0x7c, 0xca, 0x69, 0x41, 0x37, 0xa0, 0x66, 0x1e, 0x3b, 0x5e,
	0xb7, 0xda, 0xf3, 0x89, 0x2d, 0x30, 0x81, 0xf6, 0x5b, 0x2e, 0x95, 0xc3, 0x4a, 0xc2, 0x64, 0x2e,
	0x32, 0xa9, 0x59, 0x9e, 0x43, 0x6d, 0xa4, 0x58, 0x6a, 0xf1, 0xf5, 0x01, 0xde, 0xe5, 0xf5, 0x62,
	0x84, 0xd8, 0x01, 0xfc, 0xd3, 0x83, 0xd6, 0x46, 0xf3, 0x92, 0x76, 0xaf, 0xc8, 0x17, 0x3b, 0x02,
	0x5f, 0x2b, 0xd2, 0x87, 0x56, 0xd2, 0x79, 0xc1, 0x8c, 0xee, 0x03, 0x62, 0x8b, 0xc1, 0x8f, 0x2a,
	0xec, 0x2f, 0x4f, 0x0c, 0x9d, 0x42, 0xf3, 0xf5, 0x82, 0x51, 0xc5, 0xdc, 0x9b, 0x49, 0x1f, 0xdd,
	0xdf, 0x60, 0xd9, 0x92, 0xcd, 0xa0, 0x1d, 0xda, 0x44, 0x87, 0xcb, 0x44, 0x87, 0x6f, 0x74, 0xa2,
	0xf1, 0xad, 0xaf, 0xbf, 0x7e, 0x7f, 0xab, 0xb4, 0x70, 0x33, 0x2a, 0xfb, 0x11, 0x8d, 0xe3, 0xe5,
	0xf5, 0x41, 0x67, 0xd0, 0x1a, 0x32, 0x39, 0x5b, 0xf0, 0xe9, 0x0a, 0xd7, 0xbd, 0x5d, 0x8e, 0x56,
	0xa2, 0x16, 0x5c, 0xe2, 0xe3, 0xe1, 0x43, 0x43, 0x7b, 0x0d, 0xd5, 0x35, 0xed, 0x92, 0x72, 0x06,
	0x8d, 0xd5, 0x78, 0xe8, 0x1b, 0xb5, 0x5d, 0x75, 0xf0, 0x68, 0x83, 0x62, 0x7b, 0xae, 0xf0, 0x75,
	0xc3, 0x03, 0x68, 0x5f, 0xf3, 0xcc, 0xb9, 0x54, 0x68, 0x06, 0x4d, 0xc2, 0x52, 0x51, 0xfe, 0xaf,
	0xab, 0x5d, 0x07, 0xe8, 0x9c, 0x3c, 0x5e, 0x75, 0xf2, 0xea, 0xd9, 0x87, 0x93, 0x84, 0xab, 0xd3,
	0x62, 0x1a, 0xce, 0x44, 0x1a, 0x89, 0x2f, 0x22, 0x2b, 0x69, 0xb4, 0xfe, 0x73, 0xca, 0x3f, 0x25,
	0xeb, 0xef, 0xa6, 0x7b, 0x66, 0xfb, 0x93, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xc6, 0xa3,
	0x96, 0xca, 0x04, 0x00, 0x00,
}
