// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ova-meeting-api/api.proto

package ova_meeting_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddMeetingRequestV1 struct {
	Userid               uint64               `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	State                *MeetingStateV1      `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Users                []uint64             `protobuf:"varint,6,rep,packed,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AddMeetingRequestV1) Reset()         { *m = AddMeetingRequestV1{} }
func (m *AddMeetingRequestV1) String() string { return proto.CompactTextString(m) }
func (*AddMeetingRequestV1) ProtoMessage()    {}
func (*AddMeetingRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{0}
}

func (m *AddMeetingRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMeetingRequestV1.Unmarshal(m, b)
}
func (m *AddMeetingRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMeetingRequestV1.Marshal(b, m, deterministic)
}
func (m *AddMeetingRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMeetingRequestV1.Merge(m, src)
}
func (m *AddMeetingRequestV1) XXX_Size() int {
	return xxx_messageInfo_AddMeetingRequestV1.Size(m)
}
func (m *AddMeetingRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMeetingRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_AddMeetingRequestV1 proto.InternalMessageInfo

func (m *AddMeetingRequestV1) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *AddMeetingRequestV1) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddMeetingRequestV1) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *AddMeetingRequestV1) GetState() *MeetingStateV1 {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *AddMeetingRequestV1) GetUsers() []uint64 {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateMeetingRequestV1 struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Userid               uint64               `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	State                *MeetingStateV1      `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Users                []uint64             `protobuf:"varint,6,rep,packed,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateMeetingRequestV1) Reset()         { *m = UpdateMeetingRequestV1{} }
func (m *UpdateMeetingRequestV1) String() string { return proto.CompactTextString(m) }
func (*UpdateMeetingRequestV1) ProtoMessage()    {}
func (*UpdateMeetingRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{1}
}

func (m *UpdateMeetingRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMeetingRequestV1.Unmarshal(m, b)
}
func (m *UpdateMeetingRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMeetingRequestV1.Marshal(b, m, deterministic)
}
func (m *UpdateMeetingRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMeetingRequestV1.Merge(m, src)
}
func (m *UpdateMeetingRequestV1) XXX_Size() int {
	return xxx_messageInfo_UpdateMeetingRequestV1.Size(m)
}
func (m *UpdateMeetingRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMeetingRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMeetingRequestV1 proto.InternalMessageInfo

func (m *UpdateMeetingRequestV1) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateMeetingRequestV1) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *UpdateMeetingRequestV1) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateMeetingRequestV1) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *UpdateMeetingRequestV1) GetState() *MeetingStateV1 {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *UpdateMeetingRequestV1) GetUsers() []uint64 {
	if m != nil {
		return m.Users
	}
	return nil
}

type ListMeetingsRequestV1 struct {
	Limit                uint64   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMeetingsRequestV1) Reset()         { *m = ListMeetingsRequestV1{} }
func (m *ListMeetingsRequestV1) String() string { return proto.CompactTextString(m) }
func (*ListMeetingsRequestV1) ProtoMessage()    {}
func (*ListMeetingsRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{2}
}

func (m *ListMeetingsRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMeetingsRequestV1.Unmarshal(m, b)
}
func (m *ListMeetingsRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMeetingsRequestV1.Marshal(b, m, deterministic)
}
func (m *ListMeetingsRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMeetingsRequestV1.Merge(m, src)
}
func (m *ListMeetingsRequestV1) XXX_Size() int {
	return xxx_messageInfo_ListMeetingsRequestV1.Size(m)
}
func (m *ListMeetingsRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMeetingsRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_ListMeetingsRequestV1 proto.InternalMessageInfo

func (m *ListMeetingsRequestV1) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListMeetingsRequestV1) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type MeetingIDRequestV1 struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeetingIDRequestV1) Reset()         { *m = MeetingIDRequestV1{} }
func (m *MeetingIDRequestV1) String() string { return proto.CompactTextString(m) }
func (*MeetingIDRequestV1) ProtoMessage()    {}
func (*MeetingIDRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{3}
}

func (m *MeetingIDRequestV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeetingIDRequestV1.Unmarshal(m, b)
}
func (m *MeetingIDRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeetingIDRequestV1.Marshal(b, m, deterministic)
}
func (m *MeetingIDRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeetingIDRequestV1.Merge(m, src)
}
func (m *MeetingIDRequestV1) XXX_Size() int {
	return xxx_messageInfo_MeetingIDRequestV1.Size(m)
}
func (m *MeetingIDRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_MeetingIDRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_MeetingIDRequestV1 proto.InternalMessageInfo

func (m *MeetingIDRequestV1) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MeetingStateV1 struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeetingStateV1) Reset()         { *m = MeetingStateV1{} }
func (m *MeetingStateV1) String() string { return proto.CompactTextString(m) }
func (*MeetingStateV1) ProtoMessage()    {}
func (*MeetingStateV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{4}
}

func (m *MeetingStateV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeetingStateV1.Unmarshal(m, b)
}
func (m *MeetingStateV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeetingStateV1.Marshal(b, m, deterministic)
}
func (m *MeetingStateV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeetingStateV1.Merge(m, src)
}
func (m *MeetingStateV1) XXX_Size() int {
	return xxx_messageInfo_MeetingStateV1.Size(m)
}
func (m *MeetingStateV1) XXX_DiscardUnknown() {
	xxx_messageInfo_MeetingStateV1.DiscardUnknown(m)
}

var xxx_messageInfo_MeetingStateV1 proto.InternalMessageInfo

func (m *MeetingStateV1) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MeetingStateV1) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListMeetingsResponseV1 struct {
	Items                []*MeetingResponseV1 `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListMeetingsResponseV1) Reset()         { *m = ListMeetingsResponseV1{} }
func (m *ListMeetingsResponseV1) String() string { return proto.CompactTextString(m) }
func (*ListMeetingsResponseV1) ProtoMessage()    {}
func (*ListMeetingsResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{5}
}

func (m *ListMeetingsResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMeetingsResponseV1.Unmarshal(m, b)
}
func (m *ListMeetingsResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMeetingsResponseV1.Marshal(b, m, deterministic)
}
func (m *ListMeetingsResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMeetingsResponseV1.Merge(m, src)
}
func (m *ListMeetingsResponseV1) XXX_Size() int {
	return xxx_messageInfo_ListMeetingsResponseV1.Size(m)
}
func (m *ListMeetingsResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMeetingsResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_ListMeetingsResponseV1 proto.InternalMessageInfo

func (m *ListMeetingsResponseV1) GetItems() []*MeetingResponseV1 {
	if m != nil {
		return m.Items
	}
	return nil
}

type MeetingResponseV1 struct {
	Id                   *UUID                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Userid               uint64               `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	State                *MeetingStateV1      `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Users                []uint64             `protobuf:"varint,6,rep,packed,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MeetingResponseV1) Reset()         { *m = MeetingResponseV1{} }
func (m *MeetingResponseV1) String() string { return proto.CompactTextString(m) }
func (*MeetingResponseV1) ProtoMessage()    {}
func (*MeetingResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{6}
}

func (m *MeetingResponseV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeetingResponseV1.Unmarshal(m, b)
}
func (m *MeetingResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeetingResponseV1.Marshal(b, m, deterministic)
}
func (m *MeetingResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeetingResponseV1.Merge(m, src)
}
func (m *MeetingResponseV1) XXX_Size() int {
	return xxx_messageInfo_MeetingResponseV1.Size(m)
}
func (m *MeetingResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_MeetingResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_MeetingResponseV1 proto.InternalMessageInfo

func (m *MeetingResponseV1) GetId() *UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *MeetingResponseV1) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *MeetingResponseV1) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MeetingResponseV1) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *MeetingResponseV1) GetState() *MeetingStateV1 {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *MeetingResponseV1) GetUsers() []uint64 {
	if m != nil {
		return m.Users
	}
	return nil
}

type UUID struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}
func (*UUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_648ecbe2c3874e1d, []int{7}
}

func (m *UUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUID.Unmarshal(m, b)
}
func (m *UUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUID.Marshal(b, m, deterministic)
}
func (m *UUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUID.Merge(m, src)
}
func (m *UUID) XXX_Size() int {
	return xxx_messageInfo_UUID.Size(m)
}
func (m *UUID) XXX_DiscardUnknown() {
	xxx_messageInfo_UUID.DiscardUnknown(m)
}

var xxx_messageInfo_UUID proto.InternalMessageInfo

func (m *UUID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*AddMeetingRequestV1)(nil), "ova.meeting.api.AddMeetingRequestV1")
	proto.RegisterType((*UpdateMeetingRequestV1)(nil), "ova.meeting.api.UpdateMeetingRequestV1")
	proto.RegisterType((*ListMeetingsRequestV1)(nil), "ova.meeting.api.ListMeetingsRequestV1")
	proto.RegisterType((*MeetingIDRequestV1)(nil), "ova.meeting.api.MeetingIDRequestV1")
	proto.RegisterType((*MeetingStateV1)(nil), "ova.meeting.api.MeetingStateV1")
	proto.RegisterType((*ListMeetingsResponseV1)(nil), "ova.meeting.api.ListMeetingsResponseV1")
	proto.RegisterType((*MeetingResponseV1)(nil), "ova.meeting.api.MeetingResponseV1")
	proto.RegisterType((*UUID)(nil), "ova.meeting.api.UUID")
}

func init() { proto.RegisterFile("ova-meeting-api/api.proto", fileDescriptor_648ecbe2c3874e1d) }

var fileDescriptor_648ecbe2c3874e1d = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x95, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0xc4, 0x89, 0xda, 0x89, 0x94, 0xb4, 0x4b, 0x12, 0x19, 0xb7, 0x52, 0x23, 0x53,
	0x68, 0x54, 0xa9, 0xb6, 0x1c, 0xa8, 0x40, 0xdc, 0x80, 0xf4, 0x10, 0x09, 0x2e, 0x86, 0xe4, 0xc0,
	0x6d, 0x53, 0x6f, 0xd2, 0x55, 0x63, 0xaf, 0xc9, 0x6e, 0x2c, 0x01, 0xe2, 0xc2, 0x2b, 0xf0, 0x40,
	0xf0, 0x0e, 0x7d, 0x05, 0x78, 0x0f, 0xb4, 0xbb, 0x4e, 0xf3, 0xc7, 0x89, 0xa0, 0xc7, 0xde, 0x32,
	0x99, 0x6f, 0xe6, 0x37, 0xdf, 0x78, 0xd7, 0x86, 0x87, 0x2c, 0xc5, 0x67, 0x11, 0x21, 0x82, 0xc6,
	0xe3, 0x33, 0x9c, 0x50, 0x0f, 0x27, 0xd4, 0x4d, 0xa6, 0x4c, 0x30, 0x54, 0x63, 0x29, 0x76, 0xb3,
	0x94, 0x8b, 0x13, 0x6a, 0x1f, 0x8e, 0x19, 0x1b, 0x4f, 0x88, 0xa7, 0x64, 0x71, 0xcc, 0x04, 0x16,
	0x94, 0xc5, 0x5c, 0xcb, 0xed, 0x83, 0x2c, 0xab, 0xa2, 0xe1, 0x6c, 0xe4, 0x91, 0x28, 0x11, 0x9f,
	0xb3, 0xe4, 0xd1, 0x7a, 0x52, 0xd0, 0x88, 0x70, 0x81, 0xa3, 0x44, 0x0b, 0x9c, 0x5f, 0x06, 0x3c,
	0x78, 0x15, 0x86, 0xef, 0x34, 0x2e, 0x20, 0x9f, 0x66, 0x84, 0x8b, 0x81, 0x8f, 0x9a, 0x50, 0x9e,
	0x71, 0x32, 0xa5, 0xa1, 0x55, 0x68, 0x19, 0x6d, 0x33, 0xc8, 0x22, 0x54, 0x87, 0x92, 0xa0, 0x62,
	0x42, 0xac, 0x62, 0xcb, 0x68, 0xef, 0x06, 0x3a, 0x40, 0x2e, 0x98, 0x21, 0x16, 0xc4, 0x32, 0x5b,
	0x46, 0xbb, 0xd2, 0xb1, 0x5d, 0x4d, 0x75, 0xe7, 0x54, 0xf7, 0xc3, 0x9c, 0x1a, 0x28, 0x1d, 0x3a,
	0x87, 0x12, 0x17, 0xb2, 0xa0, 0xa4, 0x0a, 0x8e, 0xdc, 0x35, 0xcb, 0x6e, 0x36, 0xcf, 0x7b, 0x29,
	0x1a, 0xf8, 0x81, 0x56, 0x4b, 0xb8, 0x1c, 0x83, 0x5b, 0xe5, 0x56, 0xb1, 0x6d, 0x06, 0x3a, 0x70,
	0x6e, 0x0c, 0x68, 0xf6, 0x13, 0xd9, 0x37, 0xe7, 0xa2, 0x0a, 0x05, 0x1a, 0x5a, 0x86, 0x1a, 0xb5,
	0x40, 0xc3, 0xfb, 0xe4, 0xea, 0x02, 0x1a, 0x6f, 0x29, 0x17, 0x59, 0x09, 0x5f, 0x78, 0xaa, 0x43,
	0x69, 0x42, 0x23, 0x2a, 0x94, 0x2d, 0x33, 0xd0, 0x81, 0x74, 0xc6, 0x46, 0x23, 0x4e, 0xc4, 0xdc,
	0x99, 0x8e, 0x9c, 0x63, 0x40, 0x59, 0x8b, 0x5e, 0x77, 0xeb, 0x5e, 0x9c, 0x67, 0x50, 0x5d, 0x9d,
	0x6d, 0x49, 0x61, 0xaa, 0xcd, 0x21, 0x30, 0x63, 0x1c, 0x11, 0xd5, 0x7d, 0x37, 0x50, 0xbf, 0x9d,
	0x00, 0x9a, 0xab, 0x23, 0xf2, 0x84, 0xc5, 0x5c, 0x56, 0xbf, 0x80, 0x52, 0x4f, 0x90, 0x88, 0x5b,
	0x46, 0xab, 0xd8, 0xae, 0x74, 0x9c, 0x6d, 0x9b, 0x58, 0x94, 0x04, 0xba, 0xc0, 0xf9, 0x63, 0xc0,
	0x7e, 0x2e, 0x89, 0x1e, 0xdf, 0x4e, 0x53, 0xe9, 0x34, 0x72, 0xcd, 0xfa, 0xfd, 0x5e, 0xf7, 0xbe,
	0x3d, 0xde, 0x43, 0x30, 0xe5, 0xd8, 0x32, 0x9b, 0xe2, 0xc9, 0x8c, 0x64, 0x0f, 0x43, 0x07, 0x9d,
	0x9f, 0x26, 0xec, 0xcc, 0xd7, 0x8a, 0xae, 0xa1, 0xf6, 0x66, 0x4a, 0x16, 0xc7, 0x7b, 0xe0, 0xa3,
	0xe3, 0x1c, 0x7b, 0xc3, 0x1d, 0xb6, 0x9b, 0x39, 0x4b, 0x17, 0xf2, 0xd5, 0xe0, 0xd8, 0xdf, 0x6f,
	0x7e, 0xff, 0x28, 0xd4, 0x9d, 0x9a, 0x97, 0xfa, 0x1e, 0x0e, 0xc3, 0xf9, 0x7b, 0xe8, 0xa5, 0x71,
	0x8a, 0x18, 0xd4, 0x56, 0xee, 0xd2, 0xc0, 0x47, 0x27, 0xf9, 0x85, 0x6f, 0xbc, 0x6d, 0x5b, 0x79,
	0x07, 0x8a, 0xd7, 0x70, 0xf6, 0x24, 0x2f, 0xeb, 0xe3, 0x7d, 0xa5, 0xe1, 0x37, 0x09, 0x4c, 0x61,
	0xbf, 0x4b, 0xf8, 0xe5, 0x94, 0x0e, 0x97, 0x90, 0x8f, 0xb6, 0xed, 0x76, 0xe9, 0x10, 0xdb, 0xff,
	0x71, 0xaa, 0x1c, 0x4b, 0xa1, 0x11, 0xca, 0xa1, 0x11, 0x87, 0xea, 0xf2, 0xe1, 0x1d, 0xf8, 0xe8,
	0x49, 0xae, 0xdf, 0xc6, 0x0b, 0x68, 0x9f, 0xfc, 0x43, 0x77, 0x0b, 0xdf, 0x53, 0x70, 0x40, 0x3b,
	0x12, 0x3e, 0xa1, 0x5c, 0xa0, 0x2b, 0xa8, 0x05, 0x24, 0x62, 0xe9, 0x5d, 0xad, 0x6e, 0xdb, 0x6c,
	0x66, 0xef, 0x34, 0x67, 0xef, 0xf5, 0xf3, 0x8f, 0xe7, 0x63, 0x2a, 0xae, 0x66, 0x43, 0xf7, 0x92,
	0x45, 0x1e, 0xfb, 0xc2, 0xe2, 0x14, 0x7b, 0xeb, 0xdf, 0x9c, 0xe4, 0x7a, 0xbc, 0xfe, 0xdf, 0xb0,
	0xac, 0x10, 0x4f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xaa, 0x49, 0x7d, 0xa1, 0x06, 0x00,
	0x00,
}
